<template>
  <v-card
    class="pa-4"
    flat
    height="600px"
    img="https://magazine.zarpo.com.br/wp-content/uploads/2019/02/Confira-os-10-melhores-hoteis-em-Maceio.jpg"
  >
  </v-card>
</template>